name: Python application

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 30 10 * * *
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  test-selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.6
      - name: Set up chromedriver
        uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install
      - name: Run script
        run: |
          pipenv run python index.py
        env:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          branch: master
          commit_message: added changes by action
